/**
 * `npm run gen:theme` — emit the generated theme artifacts.
 *
 * plan.md §3.5: editing a palette in a rules file must change the video and
 * nothing else. So nothing downstream ever hardcodes a subject colour; both
 * outputs below are derived, and both are gitignored.
 *
 *   docker/python/tafel/palettes/<subject>.py   role-named colours for Manim
 *   src/app/theme.generated.css                 CSS custom properties for the UI
 *
 * ## One file per subject, not one palette.py
 *
 * plan.md §3.5 names a single `docker/python/tafel/palette.py`, but §5.2 lists its
 * exports as `KNOWN, UNKNOWN, CONSTRUCTION, RESULT, COUNTEREXAMPLE, FOCUS` — the
 * *mathematics* role set. Physics and chemistry have different roles, so a single
 * file would have to export all sixteen names at once, and a mathematics scene
 * could then legally reach for `FORCE`. That would weaken the §3.3 guarantee: the
 * point of exporting only role names is that a palette violation *cannot be
 * written*, and a scene using another subject's role is exactly such a violation.
 *
 * Emitting one file per subject keeps the guarantee exact. The helper module is
 * copied per job anyway (plan.md §4.10), so the job's own subject file is copied in
 * as `tafel/palette.py` and the container never sees a role it must not use.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadAllRules, framePalette } from "../src/lib/rules/loader";
import { SUBJECTS, type Subject } from "../src/lib/rules/schema";
import { contrastRatio } from "../src/lib/theme/color";
import { BRAND, CONTRAST, FRAME_GROUND } from "../src/lib/theme/tokens";

/**
 * Role key → Python constant. Only the shortenings plan.md §5.2 names explicitly;
 * every other role is its key uppercased.
 */
const CONSTANT_ALIASES: Record<string, string> = {
  known_quantity: "KNOWN",
  unknown_quantity: "UNKNOWN",
  accent_focus: "FOCUS",
};

const constantName = (role: string) =>
  CONSTANT_ALIASES[role] ?? role.toUpperCase();

const PYTHON_DIR = join("docker", "python", "tafel", "palettes");
const CSS_PATH = join("src", "app", "theme.generated.css");

function pythonModule(subject: Subject): string {
  const { config } = loadAllRules()[subject];
  const roles = config.visuals.palette;
  const elements = config.visuals.element_colours;

  const lines: string[] = [
    `"""Frame palette for ${subject}. GENERATED by \`npm run gen:theme\` — do not edit.`,
    "",
    `Source: guidelines/rules-${subject}.yaml v${config.version} (visuals.palette)`,
    "",
    "Only role names are exported. There is deliberately no way to name a colour",
    "here that the rulebook has not assigned a meaning, and the AST guard rejects",
    "raw hex literals in generated scenes — so a palette violation cannot be",
    "written rather than being caught after the fact.",
    '"""',
    "",
    `#: The ground every frame is drawn on.`,
    `GROUND = "${FRAME_GROUND}"`,
    "",
    "#: Prose font. Registered in the image via fc-cache; mathematics keeps LaTeX's",
    "#: Computer Modern through MathTex.",
    'FONT = "Inter"',
    "",
  ];

  for (const [role, hex] of Object.entries(roles)) {
    const ratio = contrastRatio(hex, FRAME_GROUND);
    const note =
      role === "accent_focus"
        ? "  # reserved: reachable only through cue()"
        : "";
    lines.push(`#: ${role.replace(/_/g, " ")} — ${ratio.toFixed(2)}:1 on GROUND`);
    lines.push(`${constantName(role)} = "${hex}"${note}`);
  }

  if (elements) {
    lines.push(
      "",
      "#: Element colours, fixed library-wide by the rulebook. Keyed by symbol",
      "#: because they are looked up dynamically, not named individually.",
      "ELEMENTS = {",
      ...Object.entries(elements).map(
        ([symbol, hex]) =>
          `    "${symbol}": "${hex}",  # ${contrastRatio(hex, FRAME_GROUND).toFixed(2)}:1`,
      ),
      "}",
    );
  }

  // The §3.2 text prohibition, made checkable inside the container rather than
  // left to the codegen prompt: below 4.5:1 a colour is legal for shapes and
  // strokes but never for a label or an equation.
  const palette = framePalette(config);
  const textSafe = Object.entries(palette)
    .filter(([, hex]) => contrastRatio(hex, FRAME_GROUND) >= CONTRAST.TEXT)
    .map(([, hex]) => hex);
  const graphicsOnly = Object.entries(palette).filter(
    ([, hex]) => contrastRatio(hex, FRAME_GROUND) < CONTRAST.TEXT,
  );

  lines.push(
    "",
    `#: Colours measured at or above ${CONTRAST.TEXT}:1 on GROUND, so legible as text.`,
    "#: The helpers that draw glyphs assert membership; the rest are strokes only.",
    "TEXT_SAFE = frozenset({",
    ...[...new Set(textSafe)].map((hex) => `    "${hex}",`),
    "})",
    "",
    graphicsOnly.length > 0
      ? `#: Graphics only, never text: ${graphicsOnly
          .map(([role, hex]) => `${role} ${hex} at ${contrastRatio(hex, FRAME_GROUND).toFixed(2)}:1`)
          .join(", ")}`
      : "#: Every colour in this palette clears text contrast.",
    "",
  );

  return lines.join("\n");
}

function css(): string {
  const all = loadAllRules();
  const lines: string[] = [
    "/* GENERATED by `npm run gen:theme` — do not edit.",
    " *",
    " * Brand tokens come from src/lib/theme/tokens.ts and dress the app UI.",
    " * Subject tokens come from the rulebook and are used only to *show* a palette",
    " * (swatches in the compliance report), never to style the app.",
    " */",
    "",
    ":root {",
    ...Object.entries(BRAND).map(([token, hex]) => `  --brand-${token.toLowerCase()}: ${hex};`),
    `  --frame-ground: ${FRAME_GROUND};`,
    "}",
  ];

  for (const subject of SUBJECTS) {
    lines.push(
      "",
      `/* ${subject} v${all[subject].config.version} */`,
      ":root {",
      ...Object.entries(framePalette(all[subject].config)).map(
        ([role, hex]) => `  --${subject}-${role.toLowerCase().replace(/_/g, "-")}: ${hex};`,
      ),
      "}",
    );
  }

  return `${lines.join("\n")}\n`;
}

mkdirSync(PYTHON_DIR, { recursive: true });
for (const subject of SUBJECTS) {
  const path = join(PYTHON_DIR, `${subject}.py`);
  writeFileSync(path, pythonModule(subject));
  console.log(`  wrote ${path}`);
}
writeFileSync(CSS_PATH, css());
console.log(`  wrote ${CSS_PATH}`);
